server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      server:
        webmvc:
          routes:
          - id: discovery-service-route
            uri: lb://discovery-service
            predicates:
              - Path=/eureka/web/**
            filters:
            - RewritePath=/eureka/web(?<segment>/?.*), $\{segment}

          - id: discovery-service-static-route
            uri: lb://discovery-service
            predicates:
              - Path=/eureka/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG