name: API Gateway CI

on:
  push:
    paths:
      - 'api-gateway/**'
  pull_request:
    paths:
      - 'api-gateway/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests for API Gateway
        run: cd api-gateway && ./mvnw clean verify

      - name: Build Docker image
        run: cd api-gateway && docker build -t api-gateway .
