name: Discovery Service CI

on:
  push:
    paths:
      - 'discovery-service/**' 
  pull_request:
    paths:
      - 'discovery-service/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests for Discovery Service
        run: cd discovery-service && ./mvnw clean verify

      - name: Build Docker image
        run: cd discovery-service && docker build -t discovery-service .
